<a href="https://colab.research.google.com/github/janaelleryana/StudyHSE/blob/main/workbook/2_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(c) В.И. Фирсанова | 2024

# Типы данных в Python

1. **Числовые типы**:
   - `int` integer, целое число `7`
   - `float` число с плавающей точкой (десятичная дробь) `7.1`

2. **Булевы перменные**:
   - `Bool` Boolean, принимает значения `True` или `False`

3. **Наборы, последовательности**:
   - `str` string, строка `"hello"`
   - `list`, список `[1, 7.1, "hello"]`, изменяемая последовательность
    - *вложенный список* состоит из множества списков `[[0, 1, 2], [3, 4]]`
   - `tuple`, кортеж `(1, 7.1, "hello), неизменяемая последовательность
    - в кортежах нельзя удалять, добавлять данные; они занимают меньше памяти
   - `dict`, dictionary, словарь `{"number": 1, "word": "hello"}`, пары ключей и значений (key-query)
    - в этом примере ключами будут `"number"` и `"word"`, а значениями - `1` и `"hello"`
  - `set`, множество, неупорядоченный набор уникальных элементов `{1, 2, 3}`
  - `frozenset`, неизменяемое множество (аналог кортежа по отношению к спискам)

4. **None**:
   - `None` можно использовать для создания пустого элемента, как плейсхолдер в функции, для проверки факта наличия объекта в переменной и т.д.

Задачи

1. Угадай число

In [2]:
import random # библиотека для генерации случайных чисел

# генерируем случайное целое число (random integer) от 0 до 10
# функция randint принимает два аргумента: диапазон генерации
magic_number = random.randint(0, 10)

# запросите у пользователя ввод числа
user_number = int(input("Введите число от 0 до 10"))

if user_number == magic_number: # проверка на совпадение значений
  print('Поздравляю, вы угадали!')
else:
  print('А вот и нет! Это число', magic_number)

Введите число от 0 до 107
А вот и нет! Это число 2

Обратите внимание на строку `print('А вот и нет! Это число', magic_number)`

`print` может принимать несколько аргументов через запятую и выводить на экран их все!

Используйте это в следующем задании.

2. Приветствие

In [4]:
# запросите у пользователя его имя
# вспомните, чем input(int()) отличается от input()
user_name = input("Введите Ваше имя: ")

# выведите на экран любое приветствие для пользователя
print("Привет,", user_name + "!")

Введите Ваше имя: Яна
Привет, Яна!

3. Конвертер температур

In [5]:
# запросите у пользователя температуру в градусах Цельсия:
# это должно быть дробное числом (float)
celsius = float(input("Введите температуру в градусах Цельсия: "))

# конвертируйте температуру из градусов Цельсия в градусы Фаренгейта:
# вспомните или найдите формулу и используйте арифметические операции python для расчетов
fahrenheit = (celsius * 9/5) + 32

# выведите результат на экран:
# используйте любые текстовые формулировки, чтобы показать число,
# которое вы получили от пользователя, и результат расчетов
print("Температура в градусах Цельсия", celsius)
print("Температура в градусах Фаренгейта", fahrenheit)

Введите температуру в градусах Цельсия: 32
Температура в градусах Цельсия 32.0
Температура в градусах Фаренгейта 89.6

Как вывести на экран несколько строк?

- Можно вызвать `print` несколько раз

```
print('Вот первая строка')
print('А это вторая строка')
```
- Можно использовать `\n` - символ новой строки

```
print('Вот первая строка \n А это вторая строка')
```

4. Округление и вывод с помощью новой строки

In [32]:
# результат расчетов в задаче 3 сохранился в переменных
# воспользуемся этим преимуществом!

# округлите оба значения температур в градусах Цельсия и в градусах Фаргентейта
# вы можете преобразовать результат к виду целого числа с помощью int(n); n - число для преобразования
# либо воспользоваться функцией round(n, k), указав в аргументах функции количество знаков после запятой k
# попробуйте оба варианта!
celsius_int = int(celsius)
fahrenheit_int = int(fahrenheit)

celsius_round = round(celsius, 1)
fahrenheit_round = round(fahrenheit, 1)

# теперь выведите на экран оба числа
# сделайте это в одну строчку кода:
# используйте символ новой строки, подумайте, куда его добавить
print(f"int: {celsius_int}, {fahrenheit_int}\nround: {celsius_round}, {fahrenheit_round}")

int: 32, 89
round: 32.0, 89.6

В задании 4 нам может помочь свойство конкатенации строк.

`print('Hello' + ' ' +'World')`

Но сложение строки с числом невозможно в питоне. Что делать?

5. Конвертирование типов данных

In [44]:
# преобразуйте округленные значения температур к виду строк, применив str(n),
# где n - то, что вы хотите преобразовать к виду строки
celsius_str = str(celsius_round)
fahrenheit_str = str(fahrenheit_round)

# выведите на экран результат:
# используйте конкатенацию строк вместо запятой в функции print
print("Температура в Цельсиях:" + celsius_str + "Температура в Фаренгейтах:" + fahrenheit_str )

Температура в Цельсиях:32.0Температура в Фаренгейтах:89.6

Чтобы преобразовать один тип данных в другой, мы вызываем функцию, обозначающую этот тип.

Закрепим новый материал.

6. Калькулятор

In [45]:
# запросите у пользователя 2 целых числа
# выполните операции сложения, вычитания, умножения и возведения каждого из чисел во вторую степень
# выведите результат на экран

num1 = int(input("Введите первое целое число: "))
num2 = int(input("Введите второе целое число: "))

sum_result = num1 + num2
diff_result = num1 - num2
mult_result = num1 * num2
square_num1 = num1 ** 2
square_num2 = num2 ** 2

print("Сложение:", sum_result)
print("Вычитание:", diff_result)
print("Умножение:", mult_result)
print("Квадрат первого числа", square_num1)
print("Квадрат второго числа", square_num2)

Введите первое целое число: 3
Введите второе целое число: 5
Сложение: 8
Вычитание: -2
Умножение: 15
Квадрат первого числа 9
Квадрат второго числа 25

7. Анкета

In [48]:
# вспомним множественное присваивание в python
# a, b, c = 0, 1, 2
# используйте множественное присваивание,
# чтобы одной строчкой кода запросить у пользователя имя, возраст и профессию
# выведите на экран полученную информацию

name, age, profession = input("Введите имя, возраст и профессию через пробел: ").split()

print("Имя:", name)
print("Возраст:", age)
print("Профессия:", profession)

Введите имя, возраст и профессию через пробел: Яна 27 переводчик
Имя: Яна
Возраст: 27
Профессия: переводчик

8. Поменять местами переменные

In [50]:
# множественное присваивание иногда очень полезно
# запросите у пользователя две любые переменные
# это может быть строка или число, на ваш выбор

# поменяйте их местами одной строчкой кода:
# запишите в первую переменную информацию из второй,
# а во вторую переменную - информацию из первой, используя множественное присваивание

# выведите на экран промежуточные и итоговые результаты

a = input("Введите первую переменную: ")
b = input("Введите вторую переменную: ")

# Вывод промежуточных значений
print(f"До обмена: a = {a}, b = {b}")

# Множественное присваивание для обмена значениями
a, b = b, a

# Вывод после обмена
print(f"После обмена: a = {a}, b = {b}")

Введите первую переменную: 8
Введите вторую переменную: 9
До обмена: a = 8, b = 9
После обмена: a = 9, b = 8

9. Дописать функцию

In [55]:
# чаще мы используем множественное присваивание в фунциональном программировании
# например, эта функция считает сумму и произведение двух чисел
# функция принимает на вход (почти как input!) 2 числа
# эти числа запишутся в переменные a и b
def sum_and_product(a, b):
    # напишите здесь код для расчета суммы чисел a и b
    total_sum = a + b
    # а сюда допишите код для подсчета их произведения
    product = a * b
    # функция возвращает результат подсчета - два новых числа
    return total_sum, product

# настало время множественного присваивания
# мы вызывает функцию sum_and_product и передаем ей в качестве аргументов два числа - 5 и 3
# мы помним, что функция возвращает 2 новых числа,
# поэтому результат работы одной функции мы записываем в две переменные: result_sum и result_product
result_sum, result_product = sum_and_product(5, 3)

# выведите на экран result_sum и result_product
print("Сумма:", result_sum)
print("Произведение:", result_product)

Сумма: 8
Произведение: 15

10. Строка и число

In [56]:
# запросите у пользователя 2 числа, используйте str(input())
# сложите два числа, не меняя тип данных, и выведите на экран результат
# преобразуйте числа к виду нужного типа и снова сложите их, выведите результат

# это задание нам уже знакомо:
# попробуйте решить его питонично, используя как можно меньше строк кода
# какие операции можно объединить?
# в каких случаях нам не нужно создавать дополнительные переменные?


a, b = str(input("Введите первое число: ")), str(input("Введите второе число: "))
print("Конкатенация строк:", a + b)
print("Сумма чисел:", int(a) + int(b))

Введите первое число: 6
Введите второе число: 8
Конкатенация строк: 68
Сумма чисел: 14